name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        shell: bash
        run: |
          mkdir -p contents
          for i in $(seq 1 1000); do
            mkdir -p contents/dir$i
            for j in $(seq 1 100); do
              dd if=/dev/urandom of=contents/dir$i/file$j.txt bs=1024 count=10 2>&1 >/dev/null
            done
          done
          
      - name: Timings
        shell: bash
        run: |
          section() {
            echo ""
            echo "$*"
            echo "$*" | sed 's/./-/g'
          }
        
          which tar > /dev/null && {
            section "Tar Version"
            tar --version
          
            section "Tar Create"
            time tar -cf contents_tar.tar contents/ 2>&1
            
            section "Tar Extract"
            mkdir -p extracted_tar
            time tar -xf contents_tar.tar -C extracted_tar/ 2>&1
            
            section "Tar Size"
            ls -al contents_tar.tar
          } || echo "tar not found"
          
          which gtar > /dev/null && {
            section "GTar Version"
            gtar --version
            
            section "GTar Create"
            time gtar -cf contents_gtar.tar contents/ 2>&1
            
            section "GTar Extract"
            mkdir -p extracted_gtar
            time gtar -xf contents_gtar.tar -C extracted_gtar/ 2>&1
        
            section "GTar Extract Tar"
            mkdir -p extracted_tar_with_gtar
            time gtar -xf contents_tar.tar -C extracted_tar_with_gtar/ 2>&1
            
            section "GTar Extract - Delay Directory Restore"
            mkdir -p extracted_gtar
            time gtar -xf contents_gtar.tar -C extracted_gtar/ --delay-directory-restore 2>&1
        
            section "GTar Extract Tar - Delay Directory Restore"
            mkdir -p extracted_tar_with_gtar
            time gtar -xf contents_tar.tar -C extracted_tar_with_gtar/ --delay-directory-restore 2>&1
            
            section "GTar Size"
            ls -al contents_gtar.tar
          } || echo "gtar not found"
