name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        shell: bash
        run: |
          mkdir -p contents
          seq -w 1 100000 | xargs -n1 -I% sh -c 'dd if=/dev/urandom of=file.%.txt bs=1024 count=10' 2>&1 >/dev/null

      - name: Timings
        shell: bash
        run: |
          section() {
            echo ""
            echo "$*"
            echo "$*" | sed 's/./-/g'
          }
        
          which tar > /dev/null && {
            section "Tar Version"
            tar --version
          
            section "Tar Create"
            time tar -cf contents_tar.tar contents/
            
            section "Tar Extract"
            mkdir -p extracted_tar
            time tar -xf contents_tar.tar -C extracted_tar/
          } || echo "tar not found"
          
          which gtar > /dev/null && {
            section "GTar Version"
            gtar --version
            
            section "GTar Create"
            time gtar -cf contents_gtar.tar contents/
            
            section "GTar Extract"
            mkdir -p extracted_gtar
            time gtar -xf contents_gtar.tar -C extracted_gtar/
        
            section "GTar Extract Tar"
            mkdir -p extracted_tar_with_gtar
            time gtar -xf contents_tar.tar -C extracted_tar_with_gtar/
          } || echo "gtar not found"
